sudo: required
language: node_js
node_js: 12.21.0
services:
  -docker 
before_install:
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  -npm run coverage
  -sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=hadamafer -Dsonar.projectKey=TP-IS -Dsonar.sources='./app' -X
  -docker build -t unqpdes/todo-list-front .
after_success:
  -npm run coveralls

 
deploy:
  provider: script
  script:
    # push to dockerhub
    docker push hadamafer/node-tp-is2;
  branch: master